### ISSUE TITLE
Vil Bert 구현

### ISSUE THREAD

**Issue by leecs0503** [leecs0503/NLP_FinalProject#19]
https://arxiv.org/pdf/1908.02265.pdf
해당 논문을 읽고 모델을 구현하는 작업

**Comment by DomesticDriedJujube** [comment]
ref github) https://github.com/facebookresearch/vilbert-multi-task

**Comment by DomesticDriedJujube** [comment]
huggingface - pytorch Transformer) https://github.com/huggingface/transformers

**Comment by DomesticDriedJujube** [comment]
VILBERT = BERT의 text처리와 LXmert의 cross-modality를 적절히 섞어놓은 듯..
Paper) https://arxiv.org/pdf/1908.07490.pdf
Review) https://baekyeongmin.github.io/paper-review/lxmert-review/
